# Generated by Django 4.1.5 on 2023-01-15 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_user_introduce'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(null=True, storage=models.CharField(max_length=255, primary_key=True, serialize=False, unique=True), upload_to='profile_image'),
        ),
    ]
