# Generated by Django 4.1.5 on 2023-02-02 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_user_is_signed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bgimage',
            field=models.ImageField(null=True, upload_to='bg_image/'),
        ),
    ]
