# Generated by Django 4.1.5 on 2023-02-16 06:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, default=django.utils.timezone.now, null=True)),
                ('content', models.TextField(max_length=255, null=True)),
                ('youtube_link', models.TextField()),
                ('youtube_title', models.TextField(default='')),
                ('youtube_thumb', models.TextField(default='')),
                ('like_count', models.IntegerField(default=0)),
                ('parent_id', models.IntegerField(blank=True, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
