# Generated by Django 4.1.5 on 2023-02-16 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='youtube_thumb',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='youtube_title',
            field=models.TextField(),
        ),
    ]
